# Generated by Django 6.0.2 on 2026-03-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('owner_img_field', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='CommericialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stayType', models.CharField(choices=[('hostel', 'Hostel'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], max_length=20)),
                ('commercialName', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('usage', models.CharField(blank=True, choices=[('lease', 'Lease'), ('rent', 'Rent')], max_length=20, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
                ('owner_ship_proof', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('owner_property_photos', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial', to='HAC.owners')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorNo', models.PositiveIntegerField()),
                ('area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('commercial_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='HAC.commericialdetails')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_floors', to='HAC.owners')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, max_length=150, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('accountNo', models.CharField(blank=True, max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='HAC.owners')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentStayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stayType', models.CharField(choices=[('hostel', 'Hostel'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], max_length=20)),
                ('apartmentName', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(max_length=255)),
                ('bhk', models.CharField(choices=[('1', '1 BHK'), ('2', '2 BHK'), ('3', '3 BHK')], max_length=10)),
                ('tenantType', models.CharField(blank=True, choices=[('family', 'Family'), ('bachelors', 'Bachelors')], max_length=20, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
                ('owner_ship_proof', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('owner_property_photos', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='HAC.owners')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentFloorUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('flatNo', models.PositiveIntegerField()),
                ('bhk', models.PositiveIntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='HAC.apartmentstaydetails')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_floors', to='HAC.owners')),
            ],
        ),
        migrations.CreateModel(
            name='StayHostelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stayType', models.CharField(choices=[('hostel', 'Hostel'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], max_length=20)),
                ('hostelName', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(max_length=255)),
                ('hostelType', models.CharField(blank=True, choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coliving', 'Co-Living')], max_length=20, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
                ('owner_ship_proof', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('owner_property_photos', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_details', to='HAC.owners')),
            ],
        ),
        migrations.CreateModel(
            name='HostelFloorRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('roomNo', models.PositiveIntegerField()),
                ('sharing', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_floors', to='HAC.owners')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='HAC.stayhosteldetails')),
            ],
            options={
                'ordering': ['roomNo'],
                'unique_together': {('hostel', 'floor', 'roomNo')},
            },
        ),
    ]
