# Generated by Django 5.2.12 on 2026-03-24 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('bed', models.IntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('idUri', models.ImageField(blank=True, null=True, upload_to='identity_proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='Tenent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('identityType', models.CharField(choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN'), ('Other', 'Other')], max_length=30)),
                ('identityImage', models.ImageField(upload_to='identity_proofs/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='commercialfloor',
            options={'ordering': ['floorNo', 'sectionNo']},
        ),
        migrations.RemoveField(
            model_name='apartmentstaydetails',
            name='bhk',
        ),
        migrations.RemoveField(
            model_name='apartmentstaydetails',
            name='owner_property_photos',
        ),
        migrations.RemoveField(
            model_name='commericialdetails',
            name='owner_property_photos',
        ),
        migrations.RemoveField(
            model_name='stayhosteldetails',
            name='owner_property_photos',
        ),
        migrations.AddField(
            model_name='apartmentstaydetails',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialfloor',
            name='sectionNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commericialdetails',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owners',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='owners',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspend', 'Suspend')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='stayhosteldetails',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
