# Generated by Django 5.2.12 on 2026-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0002_tenantbeds_tenent_alter_commercialfloor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
